---
title: "Assignment3_3102_bv10"
author: "Bhuvaneswari Venkatraman(bv10)"
date: '1-Oct-2021'
output:
  html_document: 
    theme: readable
    toc: yes
---

# Set seed

```{r}
set.seed(3102)
```

# Prepare your function

## Write your own function to use LOO-CV and GCV to select the optimal span for loess.

```{r}
lo.lev <- function(x1, sp){
  # x1: n-by-1 feature vector
  # sp: a numerical value for "span"
  
  n = length(x1);
  lev = rep(0, n)
  
  ##############################################
  # YOUR CODE: Compute the diagonal entries of the 
  #            smoother matrix S and 
  #            store it in a vector "lev"
  # Tip: check how we compute the smoother matrix
  #      for smoothing spline models
  
  for(i in 1:n){
    y = rep(0, n); y[i]=1;
    yi = loess(y ~ x1, span = sp)$fitted;
    lev[i]= yi[i];
  }
  
  ##############################################
  
  return(lev)
}

onestep_CV <- function(x1, y1, sp){
  
  ##############################################
  #  YOUR CODE: 
  #  1) Fit a loess model y1 ~ x1 with span = sp, and extract 
  #     the corresponding residual vector
  #  2) Call lo.lev to obtain the diagonal entries of S
  #  3) Compute LOO-CV and GCV using formula from lecture notes
  #    [lec_W5_NonlinearRegression.pdf] page 33. 
  
  n = length(x1)
  err = y1 - loess(y1 ~ x1, span = sp)$fitted
  sdiag = lo.lev(x1, sp)
  
  cv = sum((err/(1-sdiag))^2)/n
  gcv = sum((err/(1-sum(sdiag)/n))^2)/n
  ##############################################
  
  return(list(cv = cv, gcv = gcv))
}

myCV <- function(x1, y1, span){
  # x1: feature vector of length n
  # y1: response vector of length n
  # span: a sequence of values for "span"
  
  m = length(span)
  cv = rep(0, m)
  gcv = rep(0, m)
  
  for(i in 1:m){
    tmp = onestep_CV(x1, y1, span[i])
    cv[i] = tmp$cv
    gcv[i] = tmp$gcv
  }
  return(list(cv = cv, gcv = gcv))
}
```

# Test your function

```{r}
mydata = read.csv(file = "Coding3_Data.csv")
dim(mydata)
plot(mydata$x, mydata$y, xlab="", ylab="")
```
